### ISSUE TITLE
Synthesis artifacts

### ISSUE THREAD

**Issue by jesseengel** [magenta/ddsp-vst#1]
The synthesis model seems to accumulate non-harmonic frequencies over time. It is readily apparent if you leave the plugin open for around 30 minutes and then move the tone shaping box to the lower left. The only way for the model to make non-harmonic frequencies is the synthesis model so it seems likely culprit. Most likely there is some accumulated state / loss of precision with the phase over time and applying ocassional modulo to phase might help fix it.

The Noise model also occassionally creates clicks and pops, for especially loud noise are large changes. This might be due to the lack of windowing in noise synthesis.

**Comment by nikhilbhanu** [comment]
Fixed in v1.1.0, closing.
