### ISSUE TITLE
[BUG] DDSP synth: no sound out on Mac M1

### ISSUE THREAD

**Issue by Foolevil** [magenta/ddsp-vst#10]
**Describe the bug**
No sound from DDSP synth

**System Info**
 Mac mini 2020, M1 Silicon, BIg Sur
- Ableton 11 Live Suite
-  /Volumes/1TB/Downloads/DDSP-VST_v1_0_1/VST3

**To Reproduce**
When trying to use the VST plugin showed the input pitch, so it got the midi data from my keyboard but output had
no sound. I tried to tweet it around, none.

**Comment by pschuegr** [comment]
Interesting - I'm having a similar problem with the DDSP effects VST, but my synth VST seems to work fine.  I have M1/Monterey so should have pretty similar setup.  Does your effects VST work or same problem?

**Comment by nikhilbhanu** [comment]
@Foolevil @pschuegr Please try again with the latest v1.1.0 release. I've tested it on an M1 Pro Macbook and both plugins are working fine. Closing this for now, please re-open if the issue persists along with some more details on the repro steps.

**Comment by pschuegr** [comment]
@nikhilbhanu Both the synth and FX VSTs seem to be working for me now.  Thanks!
