### ISSUE TITLE
[BUG] Unexpected crashes when using DDSP-Effect VST in Reaper / Windows 10 

### ISSUE THREAD

**Issue by markhanslip** [magenta/ddsp-vst#17]
Unexpected crashes when using DDSP-Effect VST in Reaper 

**System Info**
- Clevo PB50 i7 9750H, Windows 10
- Reaper v6.23
- v1.0.2 DDSP-Effect)

Reaper regularly crashes and closes itself immediately when using the VST. I recognise that my version of Reaper is probably really out of date and that should be my first port of call - I just thought it would be helpful to know since people will be using all sorts of setups.

**Comment by nikhilbhanu** [comment]
Please try again with the latest v1.1.0 release, the plugins work fine for me in Reaper on Windows. Closing for now, please re-open if the issue persists with steps to reproduce and a crash log/error report if possible.
