### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by jesseengel** [magenta/ddsp-vst#2]
The mac build uses TFLite, but requires additional ops from Flex Delegate. This build path seems to be broken on Windows. We have an alternative to use the C TF API and SavedModels that has shown to work initially, but more testing is needed.

**Comment by GeorvityLabs** [comment]
hoping for a windows build soon!

**Comment by meatcomputer** [comment]
Are there any preliminary build instructions for windows available that one could use to test?

**Comment by jgehrcke** [comment]
Would appreciate a Windows build, too. Thanks!

> that has shown to work initially, but more testing is needed.

If we can help let us know.

**Comment by nikhilbhanu** [comment]
Windows build is now available, closing.
