### ISSUE TITLE
[BUG] custom models not possible rn

### ISSUE THREAD

**Issue by Mrugalla** [magenta/ddsp-vst#26]
**Describe the bug**
tried that feature but when clicking on that link it lead to a github page that doesn't exist

**System Info**
ddsp v 1.0.2

**To Reproduce**
1. click on the "train new model" button.
2. click on the link "[g.co/magenta/train-ddsp-vst](https://github.com/magenta/ddsp/blob/main/ddsp/colab/demos/g.co/magenta/train-ddsp-vst)"

**Additional context**
looking forward to try that feature :)

**Comment by wilzh40** [comment]
Fixed, verified that the "Train New Model" link is fixed on v1.1.0.
