### ISSUE TITLE
[BUG] FL Studio won't scan the plugin files

### ISSUE THREAD

**Issue by TrikiNya** [magenta/ddsp-vst#29]
I tried to start using the plugin, but when I tried scanning it, it didn't pull up in the list. I unzipped the folder I downloaded and placed the VST3 files directly into one of the plugin folders it scans. Nothing

- Windows 11 Home; hp 15da0053wm
- FL Studio 20: Producer Edition v20.9.2 [build 2963] - All Plugins Edition, Windows 64-bit
-  v1.0.0, DDSP-Synth and Effect

### Reproduction

1. Download the FL Studio trial and install it
2. Click "Manage Plugins"
3. Select the folder where it should scan plugins (this should have the DDSP vst3 files)
4. Scan for plugins

### Screenshots
https://user-images.githubusercontent.com/52202914/194681295-3be6e445-ccaf-4773-9688-2757acd0e77c.mp4

**Comment by and3k5** [comment]
Renaming them from .vst3 to .dll "worked" for me.

Meaning that FL Studio the plugins. But they wont run in my case.

Now I'm getting the error 
"There was a problem opening the plugin **DDSP Synth** for an unknown reason. Please make sure it was installed correctly."

![ohno](https://user-images.githubusercontent.com/2093953/235368474-aec715dd-833c-4f3d-aaa5-667f183113eb.png)
