### ISSUE TITLE
[Feature Request] License for ddsp models.

### ISSUE THREAD

**Issue by KottV** [magenta/ddsp-vst#32]
**Is your feature request related to a problem? Please describe.**
I'm packaging DDSP-VST for Linux and all seems fine(!). But for publishing binary builds the license terms must be clear.
DDSP-VST uses models which are downloaded separately during build, and the license for that models is not mentioned.

**Describe the solution you'd like**
Ideally - the LICENSE file in the downloaded DDSP-VST-Models.zip 

**Describe alternatives you've considered**
Any mention (in the readme, source/script) what license for that models is applied.

**Additional context**
Build repository: https://build.opensuse.org/package/show/multimedia:proaudio/ddsp

**Comment by nikhilbhanu** [comment]
Hey @KottV, thanks for pointing that out, the models are also licensed under Apache 2.0. I've added a license in the model zip file to indicate the same.
