### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Andr0idz** [magenta/ddsp-vst#33]
Hi I placed both the components and VST3 in their respective folders in Library but DDSP is nowhere to be found In Live and Reaper.

Reaper shows them as a failed to scan plugins(vst3) clicking on the manual scan(from the list of failed to scan plugins) still doesn't make them visible.
What am I missing?
I am on Sierra 10.12.6 , if this makes any difference.

I hope there is a solution.

Thanks!

**Comment by nikhilbhanu** [comment]
Unfortunately, the minimum required macOS version is Mojave 10.14. You can try building the plugins yourself if you are comfortable building C++ projects using CMake. You would just need to update [this](https://github.com/magenta/ddsp-vst/blob/main/cmake/Config.cmake#L61) line with your OS version and it might work. Good luck, and please update this issue if you manage to get it working on Sierra!
