### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AminaNazari** [magenta/ddsp-vst#8]
Plug-in won't open using Ableton 10 + 11 or Max/Msp 8. 
Says plug-in cannot be opened in both applications.

**System Info**
- What machine/OS you're using: Macbook Pro 10.13.6 OS High Sierra
- Your DAW and version: Ableton 10+11 & Max/MSP 8 

Would love to use the plug-in. I hope it can be fixed ASAP

**Comment by jesseengel** [comment]
Hi, it seems likely this is an issue with the older OS, as in #5 

We just released a new version that should work with older versions of macOS (https://g.co/magenta/ddsp-vst-mac) can you try it out and see if it works for you? Thanks!
