### ISSUE TITLE
[BUG] Can't load trained model in AU in Ableton

### ISSUE THREAD

**Issue by Louismac** [magenta/ddsp-vst#9]
**Describe the bug**
I trained a model using the Colab provided, put the unzipped download in the Models/ folder but it doesnt show up in the plug ins. Only pre-shipped models are in the list (I'm guessing my model should be added to this list?)

**System Info**
 Macbook Pro 2020, M1 Silicon, Monterey
Ableton 10
Audio Unit v 1.01

**To Reproduce**
Traine model using the Colab provided, put the unzipped download in the Models/ folder, hit refresh

**Screenshots**

<img width="1460" alt="Screenshot 2022-06-03 at 17 37 16" src="https://user-images.githubusercontent.com/1238876/171908157-134727b1-57ad-4c8d-ae4d-b88ae1fb6859.png">

**Additional context**
Anything else we should know?

**Comment by romanticamaj** [comment]
same issue here
it's very easy to reproduce
here the file I put in the dir in model file of Magenta
<img width="263" alt="image" src="https://user-images.githubusercontent.com/24642347/187150266-43dd15ee-451b-4db7-a127-ef954ae4fd72.png">

**Comment by wilzh40** [comment]
Hi, could you try directly dragging the `*.tflite` file into your model directory, instead of the entire exported directory itself?

**Comment by nikhilbhanu** [comment]
@Louismac @romanticamaj Please try again with the latest v1.1.0 release. As @wilzh40 mentioned, you would only need to drag the trained `*.tflite` into the models directory. We will update the Colab instructions to reflect this. Closing this for now, please re-open if the issue persists along with the trained model zip file if possible.
